os:
  - linux

language: go
env:
  global:
    BINARIES="keygen producers"

before_script:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure

script:
  - |
      if [ "$TRAVIS_OS_NAME" = linux ]; then
        for binary in $BINARIES; do
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -ldflags '-w -extldflags "-static"' -o $binary $binary.go
        done
      fi
