os:
  - linux

language: go
env:
  global:
    - BINARIES="keygen producers"
    - secure: "b1UWulnFxQSr6bp/E3shH5ib4ye5/TRcaXmJiw6YiQ3xPkwhKug6bxKHAHH+5o2MsJEhc0UciXWzVw3ac8sS3HWECjLaM6/o112iWfjh4VtOSa+N/tOspyDh5UvUkxF8m7vwbXyKPRflRc5NZ8awJaC64+o1C2+YOVaLCKRlo1/dCHnXjnHwXWRilbnI8WTptLs0+XeFtJugOqYl2l1okp/joEd0g0tpZzj9KhUOGwBqI6pZwp1qvws5LyEouqj2lgd3j3MNw5NWcayRer0PFq6BxlF9x6Oj16tSBvcCOU3z1aCK9dkoC6G7irqjf94LGyT+89xec508/tjsd2NT9s4jdW1LWQ3xCkILpCKw9hSuGwSqLpDY1KQnZose8Zv3+qqEeRPFxts9o6MKg3o5/sKcOs9VtO5EOgeue31OXHYiF/uHVX2+Ey47q/u7DG+q21JcTLrXNvNwzoJcr0Lda3cg2NjnQpNYVbBds0XDTmeeNJjEE31MH4b4ccCoD+I6qsrQReMsvyZfGSjfTpZOdkdPUmUFYYSOIqXyquSkDY2OOQxfv0AYiMnV9iZMma8vHEv57Z1LCPp1+gGw3yUvtdnQhNHWiNvW+hIemKeu3DhrRJnrqB0o1vRHKzKba1sooLNnVwqKGEq1sU1IRmQpOqlfEKUxiaWCFr5UBiiu8Rk="

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure
  - mkdir dist

script:
  - |
      if [ "$TRAVIS_OS_NAME" = linux ]; then
        for binary in $BINARIES; do
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -ldflags '-w -extldflags "-static"' -o dist/$binary $binary/$binary.go
        done
      fi

deploy:
  provider: script
  on:
    tags: true
  script: |
    go get github.com/tcnksm/ghr
    ghr -t ${GITHUB_TOKEN} -u ${TRAVIS_REPO_SLUG%/*} -r ${TRAVIS_REPO_SLUG#*/} -c ${TRAVIS_TAG} -delete ${TRAVIS_TAG} ./dist/
