version: 2

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /^v?\d+\.\d+\.\d+$/
      - publish-artifacts:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?\d+\.\d+\.\d+$/

jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/project
    environment:
      BINARIES: "keygen producers"

    steps:
    - checkout

    - restore_cache:
        keys:
        - '{{ checksum "Gopkg.toml" }}'

    - run:
        name: Build binaries
        command: |
          go get -u github.com/golang/dep/cmd/dep
          dep ensure -v && mkdir -p dist

          # update before build
          sh update.sh

          for binary in $BINARIES; do
            CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -ldflags '-w -extldflags "-static"' -o dist/${binary}_linux_amd64 build/$binary/main.go
            objcopy -S dist/${binary}_linux_amd64
          done

    - save_cache:
        key: '{{ checksum "Gopkg.toml" }}'
        paths:
          - /go/pkg/dep

    - persist_to_workspace:
        root: /go/src/project/dist
        paths:
        - ./

  publish-artifacts:
    docker:
      - image: cibuilds/github:0.12
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: Publish artifacts
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -recreate ${CIRCLE_TAG} ./artifacts/
